<?php
/**
 * Language switcher
 *
 * @see Mage_Page_Block_Switch
 *
 */
?>
<?php if(count($this->getStores())>1): ?>

    <?php
        $currStoreName = '';
        $currStoreCode = '';
        $html = array();
        $html[] = '<ul class="dropdown-content left-hand">';
        foreach($this->getStores() as $_store)
        {
            $storeName = $this->__($this->escapeHtml($_store->getName()));
            $storeId = $_store->getId();
            $storeCode = $_store->getCode(); //$storeCode = Mage::getStoreConfig('general/locale/code', $storeId);
            $css = 'style="background-image:url('. $this->getSkinUrl('images/flags/'. $storeCode .'.png') .');"';
            
            if($storeId == $this->getCurrentStoreId())
            {
                $currStoreName = $storeName;
                $currStoreCode = $storeCode;
                $html[] = '<li class="current"><span class="label dropdown-icon" '. $css .'>&nbsp;</span>'. $storeName .'</li>';
            }
            else
            {
                $html[] = '<li><a href="'. $_store->getCurrentUrl() .'"><span class="label dropdown-icon" '. $css .'>&nbsp;</span>'. $storeName .'</a></li>';
            }
        }
        $html[] = '</ul>';
    ?>

    <div class="lang-switcher dropdown">
        <a href="#" class="dropdown-heading cover">
            <span>
                <span class="label-lang"><?php echo $this->__('Language'); ?></span>
                <span id="value_language">
                	<span class="value"><?php echo $currStoreName; ?></span>
                	<span class="caret">&nbsp;</span>
               	</span>
            </span>
        </a>
        <?php echo implode('', $html); ?>
    </div>

<?php endif; ?>